#!/usr/bin/with-contenv bash

PS_RET=1
until [[ $PS_RET -eq 0 ]]; do
  sleep 1s
  ps -w ax | egrep -v grep | grep "avahi-daemon" > /dev/null
  PS_RET=$?
done
sleep 1s

echo "Start service: forked-daapd\n"
exec \
	s6-setuidgid abc /usr/sbin/forked-daapd -f \
	-P /daapd-pidfolder/forked-daapd.pid
