#!/usr/bin/with-contenv bash

PS_RET=1
until [[ $PS_RET -eq 0 ]]; do
    sleep 1s
  ps -w ax | egrep -v grep | grep "/usr/lib/bluetooth/bluetoothd" > /dev/null
  PS_RET=$?
done

echo "Start service: bluealsa"
exec \
	/usr/bin/bluealsa -p a2dp-source -p hsp-hs -p hsp-ag
