#!/usr/bin/with-contenv bash

## make folders ##
mkdir -p /config/alsa \
	/config/alsa/alsaequal \
	/config/bluetooth

## alsa ##
# configure defaults copy of conf
if [ ! -e "/defaults/asound.conf" ]; then
  cp /etc/asound.conf.orig /defaults/asound.conf
fi

# symlink conf to /conf
[[ ! -f /config/alsa/asound.conf ]] && \
	cp /defaults/asound.conf /config/alsa/asound.conf
[[ ! -L /etc/asound.conf && -f /etc/asound.conf ]] && \
	rm /etc/asound.conf
[[ ! -L /etc/asound.conf ]] && \
	ln -s /config/alsa/asound.conf /etc/asound.conf

## Bluetooth ##
# symlink conf dir to /conf dir
[[ ! -L /var/lib/bluetooth && -d /var/lib/bluetooth ]] && \
	rm -r /var/lib/bluetooth
[[ ! -L /var/lib/bluetooth ]] && \
	ln -s /config/bluetooth /var/lib/bluetooth

## amixer-webui ##
# configure defaults copy of conf
if [ ! -e "/defaults/amixer-webui.conf" ]; then
  cp /etc/amixer-webui.conf.orig /defaults/amixer-webui.conf
fi

# symlink conf to /conf
[[ ! -f /config/alsa/amixer-webui/amixer-webui.conf ]] && \
	cp /defaults/amixer-webui.conf /config/alsa/amixer-webui.conf
[[ ! -L /etc/amixer-webui.conf && -f /etc/amixer-webui.conf ]] && \
	rm /etc/amixer-webui.conf
[[ ! -L /etc/amixer-webui.conf ]] && \
	ln -s /config/alsa/amixer-webui.conf /etc/amixer-webui.conf

## permissions ##
if [ -d /dev/snd ]; then
  chmod 0766 /dev/snd/*
fi

chown -R abc:abc /config
